### ISSUE TITLE
Multiple code problems (when trying to install)

### ISSUE THREAD

**Issue by cole-ragingbits** [nterms/yii2-mailqueue#1]
migrations/m150302_051519_mailqueue_init.php

Yii::$pp->get

...should be...

Yii::$app->get

**Comment by cole-ragingbits** [comment]
MailQueue.php

InvalidConfigException
...should be...
\yii\base\InvalidConfigException

...also, the line that throws that exception needs to be temporarily commented out just so the migration works.  Maybe put in a check whether you're _in_ a migration and don't throw the exception if you are?

**Comment by cole-ragingbits** [comment]
Now I discover the "Queue.php" file has class name "Course" instead?  Dude, this thing is really buggy...

**Comment by nterms** [comment]
hi, thanks for the feedback, this extension is still in development and needs some more review before use. I'd attempt fixing them soon. However please feel free to send a pull request if you found and fix some issue. Apologies for not mentioning this on readme and wasting your time

**Comment by cole-ragingbits** [comment]
I'll consider that, thank you for your efforts though!  :)

**Comment by cole-ragingbits** [comment]
Pull request submitted

**Comment by jacmoe** [comment]
This issue can be closed, I think :)
