### ISSUE TITLE
Extend MailQueue.php with my own component which extends \yii\swiftmailer\Mailer

### ISSUE THREAD

**Issue by BenasPaulikas** [nterms/yii2-mailqueue#11]
Any possibilities for that ?

**Comment by nterms** [comment]
Only way I can imagine doing that is to fork this repo and use your own implementation of the swifrmailer in the place of `use yii\swiftmailer\Mailer`

**Comment by BenasPaulikas** [comment]
Yii2 user module implemented that and after looking at their code it's not hard at all :+1:
