### ISSUE TITLE
Attachment not sent

### ISSUE THREAD

**Issue by carnao** [nterms/yii2-mailqueue#17]
Hello, i'm tryng to convert some code that sends single messages to use the queue.
The code is like this:
\Yii::$app->mailqueue->compose('generic',[
                        'content' => $msg
                ])
            ->setFrom('email@email.com')
            ->setTo($iscritto->email)
            ->setSubject('Attestato di partecipazione al corso '.$corso->titolo)
            ->setTextBody('In allegato inviamo l\'attestato di partecipazione alla sessione del '.$model->dataV.' per il corso '.$model->corso->titolo)
            ->attachContent($attach, ['fileName' => 'attestato.pdf', 'contentType' => 'application/pdf'])  
            ->queue();

The problem is that the attachment is not sent when i process the queue; it is not even saved in the db table of the queue

What can be the issue?

**Comment by thomassb** [comment]
It looks like there is no provision for attaching documents.
This also effects embedded images.

**Comment by BBrunekreeft** [comment]
In Message::queue(), all separate fields are serialized and placed in the database (to, from, subject, etc).
Why not change Message::queue() so it serializes the complete Message object and places this in the database (in a new TEXT column: message)?
The only thing MailQueue::process() has to do now, is deserialize this message and use the send() method of this deserialized object.

When using this approach, you kan place all kinds of messages with attachments and inline images in the queue.

**Comment by nterms** [comment]
@BBrunekreeft Thanks a lot for your suggestion, however at this moment I can't find time to work on this. You are welcome to do a pull request if you have a fix.

**Comment by BBrunekreeft** [comment]
See pull request #23 
Did some tests and it works for me.
Note: you have to add attachements as Dynamic Content for this to work
Because if using the Swift_Attachment::fromPath() method, at the time of sending, the attachment might not be available on disk anymore.

**Comment by nterms** [comment]
@BBrunekreeft merged and a new release is done. Thanks for your help.
