### ISSUE TITLE
[Bug] Error when composer update - Add column swift_message

### ISSUE THREAD

**Issue by niceapple** [nterms/yii2-mailqueue#24]
It throws error when sending email, `Setting unknown property: 
>>> 
`nterms\mailqueue\models\Queue::swift_message`

Migration can not be updated, ti throws error:
>>>
`PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'MailQueue' not found'`

`in /var/www/html/vsource-payment/vendor/nterms/yii2-mailqueue/migrations/m161111_080914_add_swift_message_column_to_mail_queue_table.php:15`

>>>
`Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: m161111_080914_add_swift_message_column_to_mail_queue_table::longtext()'`

**Comment by nterms** [comment]
Thanks @niceapple for informing this. Fixed the issue and made a release. Please update. Didn't test it though. Please close this issue if that works for you.

**Comment by niceapple** [comment]
Thank you so much @nterms, it's fixed and works for me now.
