### ISSUE TITLE
File attachments to emails

### ISSUE THREAD

**Issue by component6** [nterms/yii2-mailqueue#27]
I liked your extension, thank you very much for the work done.
I customize it to your project.
But I was surprised that there was no possibility of attach files to emails which fall into place.
Or I do not understand something?
I suppose that you can add another column to the database, which would be stored in the path to the attachment files.
(Attachable files, respectively, should be pre-loaded)
I think that this feature would be very useful.
Thank you.
Sorry for my English

-------------------------
Мне понравилось ваше расширение, огромное спасибо за проделанную работу.
Настроил его на своем проекте.
Но я удивился, что нет возможности вложить файлы к письмам которые попадают в очередь.
Или я что то не понял?
Предполагаю, что можно, добавить еще один столбец в базу данных, в котором бы хранились пути до прикрепляемых файлов.
(прикрепляемые файлы, соответственно должны быть заранее загруженны)
Считаю, что данная возможность была бы весьма полезной.
Спасибо.

**Comment by nterms** [comment]
Hi @component6, Thank you for the feedback. I agree that the attachment is an essential part of an email. However it's quite hard to make the time for development right now. If someone like to work on this, I'm happy to accept a pull request.

**Comment by BBrunekreeft** [comment]
This is fixed a while ago (see issue #17 and pull request #23)
You have to add attachements as Dynamic Content for this to work.
([http://swiftmailer.org/docs/messages.html#attaching-dynamic-content](http://swiftmailer.org/docs/messages.html#attaching-dynamic-content))

Like this:

```
$message = \Yii::$app->mailqueue->compose(
    'layouts/email', [
       'HTMLContent' => $html,
       'title'       => $subject,
    ]
)
    ->setFrom(['info@examle.com' => 'Example'])
    ->setTo('example@example.com')
    ->setSubject('Mail with attachment');

$attachment = \Swift_Attachment::newInstance()
    ->setFilename('filename.txt')
    ->setContentType(mime_content_type($attachFile))
    ->setBody(file_get_contents($attachFile));

$message->getSwiftMessage()->attach($attachment);
$message->queue($this->timeToSend);
```
