### ISSUE TITLE
can not send email

### ISSUE THREAD

**Issue by Foina** [nterms/yii2-mailqueue#40]
Dear Sir,

I come across a problem, the yii2-mailqueue cannot send mail, I saw the message in MySQL database but it not dequeue and there is no error message. I am so confused about it.

**Comment by nterms** [comment]
Did you set the CRON job properly (if that 's how you are planing to process the queue) and do you see any error messages in log files?

**Comment by Foina** [comment]
Thank you for your reply! CRON? What is that? And I have another problem on a test machine, the queue works well but I can not receive the email

**Comment by nterms** [comment]
I believe you understand you need to call `Yii::$app->mailqueue->process();` to process your queue and send out the emails. You may [set a CRON job](https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/) to automate this process. Please refer to `RADME.md` for a better understanding.

**Comment by Foina** [comment]
yes I set CRON and the program on my computer can work just on test machine have that kind of problem

**Comment by nterms** [comment]
Perhaps I can help you more if you can share some more details on the error your are getting on your test server. What do you see on error logs?
