### ISSUE TITLE
Migrations fails 

### ISSUE THREAD

**Issue by Eseperio** [nterms/yii2-mailqueue#45]
Migration fails because method init of the module throws an exception on init method if table is not found. And migrations request module instance to get the table name. which triggers init.

**Comment by dev3k** [comment]
same here

**Comment by BBrunekreeft** [comment]
This is fixed in pull request #46.
It's just not released yet.
@nterms, can you do a new release?

**Comment by nterms** [comment]
@Eseperio @dev3k @BBrunekreeft I'm sorry guys did not have time for this. Released v 0.0.16
