### ISSUE TITLE
Problem with public function queue

### ISSUE THREAD

**Issue by bohdan-vorona** [nterms/yii2-mailqueue#9]
![ashampoo_snap_2016 03 23_10h46m27s_001_](https://cloud.githubusercontent.com/assets/5950639/13980015/b39eb798-f0e4-11e5-9e6a-4086c4eb0067.jpg)

You can't use **time()** as a default parameter for the function.

**Comment by bohdan-vorona** [comment]
**The solution is:**

```
    public function queue($time_to_send = false)
    {
            if (!$time_to_send) {
                $time_to_send = time();
            }
            ....
        }
```

**Comment by nterms** [comment]
This was fixed on master branch long time ago. However didn't create a new release after fixing the issue. Sorry for that :)

Please update to v 0.0.3 to get rid of this issue.
